version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: User
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD:  ecommerce-redis-p@ss
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata: {}
  redisdata: {}
